version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    container_name: personal-blog-db
    ports:
      - protocol: tcp
        published: 3306
        target: 3306
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_DATABASE: personal_blog
    