version: "3.7"
services:
  app:
    build:
      args:
        user: fauzan
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: personal-blog-app
    container_name: personal-blog-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - pb

  db:
    image: mariadb:latest
    container_name: personal-blog-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - pb

  nginx:
    image: nginx:alpine
    container_name: personal-blog-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - pb

networks:
  pb:
    driver: bridge